---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: ecommerce
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1.5Gi
    limits.cpu: "2.5"
    limits.memory: 10Gi
    

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1.5Gi
    limits.cpu: "1"
    limits.memory: 3Gi
  

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "0.05"
    requests.memory: 0.3Gi
    limits.cpu: "0.15"
    limits.memory: 0.5Gi
   
